apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "jet-helm-chart.fullname" . }}-supavisor-session
  labels:
    {{- include "jet-helm-chart.supavisorLabels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: HostSNI(`*`)
      kind: Rule
      services:
        - name: {{ include "jet-helm-chart.fullname" . }}-supavisor
          port: 5452
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "jet-helm-chart.fullname" . }}-supavisor-transaction
  labels:
    {{- include "jet-helm-chart.supavisorLabels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: HostSNI(`*`)
      kind: Rule
      services:
        - name: {{ include "jet-helm-chart.fullname" . }}-supavisor
          port: 6543
