remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
namespace: default
release-label: app.kubernetes.io/namespace
additional-commands:
  - helm unittest --strict {{ .Path }}
