# TODO: 1. Change `appIngressroute` to `appIngressroutes`
# 2. Delete this after the version 2.0.0
{{- range .Values.appIngressroute }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "application-chart-template.fullname" $ }}-{{ .name }}-web
  namespace: {{ $.Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
    # TODO: 1. Update multiple service ports. Input multiple service ports using list.
    # 2. Delete this after the version 2.0.0
    {{- if $.Values.service.port }}
    - match: {{ include "application-chart-template.applicationHosts" $ }} && PathPrefix(`{{ .path }}`)
      kind: Rule
      services:
        - name: {{ include "application-chart-template.fullname" $ }}
          port: {{ $.Values.service.port }}
      middlewares:
        {{- include "application-chart-template.webMiddlewares" $ | nindent 8}}
    {{- else }}
    - match: {{ include "application-chart-template.applicationHosts" $ }} && PathPrefix(`{{ .path }}`)
      kind: Rule
      services:
        - name: {{ include "application-chart-template.fullname" $ }}
          port: {{ include "application-chart-template.ingressServicePort" (dict "ports" $.Values.service.ports "servicePortName" .servicePortName) }}
      middlewares:
        {{- include "application-chart-template.webMiddlewares" $ | nindent 8}}
    {{- end }}

---
{{- if $.Values.applicationTLS }}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "application-chart-template.fullname" $ }}-{{ .name }}-websecure
  namespace: {{ $.Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    # TODO: 1. Update multiple service ports. Input multiple service ports using list.
    # 2. Delete this after the version 2.0.0
    {{- if $.Values.service.port }}
    - match: {{ include "application-chart-template.applicationHosts" $ }} && PathPrefix(`{{ .path }}`)
      kind: Rule
      services:
        - name: {{ include "application-chart-template.fullname" $ }}
          port: {{ $.Values.service.port }}
      middlewares:
        {{- include "application-chart-template.websecureMiddlewares" $ | nindent 8}}
    {{- else }}
    - match: {{ include "application-chart-template.applicationHosts" $ }} && PathPrefix(`{{ .path }}`)
      kind: Rule
      services:
        - name: {{ include "application-chart-template.fullname" $ }}
          port: {{ include "application-chart-template.ingressServicePort" (dict "ports" $.Values.service.ports "servicePortName" .servicePortName) }}
      middlewares:
        {{- include "application-chart-template.websecureMiddlewares" $ | nindent 8}}
    {{- end }}
  tls:
    {{- if $.Values.applicationTLS.certResolver }}
    certResolver: {{ $.Values.applicationTLS.certResolver }}
    {{- else if $.Values.applicationTLS.TLSSecret }}
    secretName: {{ include "application-chart-template.fullname" $ }}-tls-secret
    {{- end }}
{{- end }}
{{- end }}

{{- range .Values.appIngressroutes }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "application-chart-template.fullname" $ }}-{{ .name }}-web
  namespace: {{ $.Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
    # TODO: 1. Update multiple service ports. Input multiple service ports using list.
    # 2. Delete this after the version 2.0.0
    {{- if $.Values.service.port }}
    - match: {{ include "application-chart-template.applicationHosts" $ }} && PathPrefix(`{{ .path }}`)
      kind: Rule
      services:
        - name: {{ include "application-chart-template.fullname" $ }}
          port: {{ $.Values.service.port }}
      middlewares:
        {{- include "application-chart-template.webMiddlewares" $ | nindent 8}}
    {{- else }}
    - match: {{ include "application-chart-template.applicationHosts" $ }} && PathPrefix(`{{ .path }}`)
      kind: Rule
      services:
        - name: {{ include "application-chart-template.fullname" $ }}
          port: {{ include "application-chart-template.ingressServicePort" (dict "ports" $.Values.service.ports "servicePortName" .servicePortName) }}
      middlewares:
        {{- include "application-chart-template.webMiddlewares" $ | nindent 8}}
    {{- end }}

---
{{- if $.Values.applicationTLS }}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "application-chart-template.fullname" $ }}-{{ .name }}-websecure
  namespace: {{ $.Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    # TODO: 1. Update multiple service ports. Input multiple service ports using list.
    # 2. Delete this after the version 2.0.0
    {{- if $.Values.service.port }}
    - match: {{ include "application-chart-template.applicationHosts" $ }} && PathPrefix(`{{ .path }}`)
      kind: Rule
      services:
        - name: {{ include "application-chart-template.fullname" $ }}
          port: {{ $.Values.service.port }}
      middlewares:
        {{- include "application-chart-template.websecureMiddlewares" $ | nindent 8}}
    {{- else }}
    - match: {{ include "application-chart-template.applicationHosts" $ }} && PathPrefix(`{{ .path }}`)
      kind: Rule
      services:
        - name: {{ include "application-chart-template.fullname" $ }}
          port: {{ include "application-chart-template.ingressServicePort" (dict "ports" $.Values.service.ports "servicePortName" .servicePortName) }}
      middlewares:
        {{- include "application-chart-template.websecureMiddlewares" $ | nindent 8}}
    {{- end }}
  tls:
    {{- if $.Values.applicationTLS.certResolver }}
    certResolver: {{ $.Values.applicationTLS.certResolver }}
    {{- else if $.Values.applicationTLS.TLSSecret }}
    secretName: {{ include "application-chart-template.fullname" $ }}-tls-secret
    {{- end }}
{{- end }}
{{- end }}
